# Dockerfile.server

FROM node:24-alpine

ARG MONGODB_URL
ENV MONGODB_URL $MONGODB_URL

RUN apk update && \
    apk upgrade && \
    apk add \
        libc6-compat \
        bash \
        git

WORKDIR /app
COPY package.json package-lock.json ./
COPY . .

ENV NODE_ENV=production
EXPOSE 3000

RUN npm ci --only=production && npm run build

CMD ["npm", "start"]
