[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "website"
version = "0.1.0"
requires-python = ">=3.9"
readme = "README.md"

dependencies = [
    "black"
]

[project.scripts]
website-start = "tools.start:main"

[tool.black]
line-length = 80
target-version = ["py38"]
