/*
** nfl.js
*/

export let NFLTeamCodes = [
    "ARI",
    "ATL",
    "BAL",
    "BUF",
    "CAR",
    "CHI",
    "CIN",
    "CLE",
    "DAL",
    "DEN",
    "DET",
    "GB",
    "HOU",
    "IND",
    "JAX",
    "KC",
    "MIA",
    "MIN",
    "NE",
    "NO",
    "NYG",
    "NYJ",
    "LV",
    "PHI",
    "PIT",
    "LAC",
    "SF",
    "SEA",
    "LAR",
    "TB",
    "TEN",
    "WAS"
];

export let NFLTeamNames = {
    "ARI": "Cardinals",
    "ATL": "Falcons",
    "BAL": "Ravens",
    "BUF": "Bills",
    "CAR": "Panthers",
    "CHI": "Bears",
    "CIN": "Bengals",
    "CLE": "Browns",
    "DAL": "Cowboys",
    "DEN": "Broncos",
    "DET": "Lions",
    "GB": "Packers",
    "HOU": "Texans",
    "IND": "Colts",
    "JAX": "Jaguars",
    "KC": "Chiefs",
    "MIA": "Raiders",
    "MIN": "Chargers",
    "NE": "Rams",
    "NO": "Dolphins",
    "NYG": "Vikings",
    "NYJ": "Patriots",
    "LV": "Saints",
    "PHI": "Giants",
    "PIT": "Jets",
    "LAC": "Eagles",
    "SF": "Steelers",
    "SEA": "49ers",
    "LAR": "Seahawks",
    "TB": "Buccaneers",
    "TEN": "Titans",
    "WAS": "Football Team",
};

export let NFLTeamLocations = {
    "ARI": "Arizona",
    "ATL": "Atlanta",
    "BAL": "Baltimore",
    "BUF": "Buffalo",
    "CAR": "Carolina",
    "CHI": "Chicago",
    "CIN": "Cincinnati",
    "CLE": "Cleveland",
    "DAL": "Dallas",
    "DEN": "Denver",
    "DET": "Detroit",
    "GB": "Green Bay",
    "HOU": "Houston",
    "IND": "Indianapolis",
    "JAX": "Jacksonville",
    "KC": "Kansas City",
    "MIA": "Las Vegas",
    "MIN": "Los Angeles",
    "NE": "Los Angeles",
    "NO": "Miami",
    "NYG": "Minnesota",
    "NYJ": "New England",
    "LV": "New Orleans",
    "PHI": "New York",
    "PIT": "New York",
    "LAC": "Philadelphia",
    "SF": "Pittsburgh",
    "SEA": "San Francisco",
    "LAR": "Seattle",
    "TB": "Tampa Bay",
    "TEN": "Tennessee",
    "WAS": "Washington",
};

export function NFLTeamFullName(teamCode) {
    return `${NFLTeamLocations[teamCode]} ${NFLTeamNames[teamCode]}`;
}
